"""Joint classical-quantum coexistence optimizer.

Turns the coexistence *calculator* into a design *tool*: given a fiber route, a
DWDM channel plan, and a quantum-security requirement, it solves for the best
classical launch power instead of sweeping by hand.

Because classical capacity is unimodal in launch power (it rises to the
Gaussian-Noise optimum, then falls) while the QKD key rate is monotonically
decreasing in launch power, the constrained optimum is simply::

    p* = min( p_GN-optimum , p_secure-boundary )

i.e. push the classical power up to its own optimum, unless QKD security forces
you to back off first.  This module finds both points (via SciPy) and returns
the operating point plus whether the QKD constraint binds.  A gradient-based
(autodiff) optimizer over more variables is the natural future upgrade.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import brentq, minimize_scalar

from iqcore.fiber import FiberSpec, SMF28
from .dv import DetectorModel, bb84_decoy_key_rate
from .cv import CVDetector
from .finite_key import FiniteKeyParams
from .protocols import mdi_qkd_key_rate, tf_qkd_key_rate
from .coexistence import (
    RamanModel, classical_capacity_bps, raman_background_yield,
    coexistence_dv_key_rate, coexistence_cv_key_rate,
)

__all__ = [
    "OperatingPoint",
    "optimize_launch_power",
    "coexistence_reach",
    "protocol_coexistence_key_rate",
    "select_best_protocol",
]

QKD_PROTOCOLS = ("dv", "cv", "mdi", "tf")


def protocol_coexistence_key_rate(protocol: str, distance_km: float,
                                  launch_dbm_per_channel: float, n_channels: int, *,
                                  fiber: FiberSpec = SMF28,
                                  detector: DetectorModel | None = None,
                                  cv_detector: CVDetector | None = None,
                                  raman: RamanModel | None = None,
                                  finite: FiniteKeyParams | None = None,
                                  mu: float = 0.5) -> float:
    """Secret-key rate of ``protocol`` under classical DWDM coexistence.

    Dispatches to the right protocol, injecting the spontaneous-Raman background
    (DV/MDI/TF) or excess noise (CV) generated by the co-propagating classical
    channels, and applies finite-key corrections where supported (DV/MDI/TF).
    """
    proto = protocol.lower()
    det = detector or DetectorModel()
    eta = fiber.transmissivity(distance_km)
    p_total = 1e-3 * 10.0 ** (launch_dbm_per_channel / 10.0) * n_channels

    if proto == "cv":
        return coexistence_cv_key_rate(
            distance_km, launch_dbm_per_channel, n_channels, fiber=fiber,
            cv_detector=cv_detector, raman=raman, finite=finite)

    bg = raman_background_yield(p_total, distance_km, fiber=fiber, raman=raman,
                               detector_efficiency=det.efficiency)
    if proto == "dv":
        return bb84_decoy_key_rate(eta, mu, detector=det, background_yield=bg,
                                   finite=finite)
    if proto == "mdi":
        return mdi_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    if proto == "tf":
        return tf_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    raise ValueError(f"protocol must be one of {QKD_PROTOCOLS}")


def select_best_protocol(distance_km: float, n_channels: int,
                         launch_dbm_per_channel: float, *,
                         protocols=QKD_PROTOCOLS,
                         fiber: FiberSpec = SMF28,
                         detector: DetectorModel | None = None,
                         cv_detector: CVDetector | None = None,
                         raman: RamanModel | None = None,
                         finite: FiniteKeyParams | None = None,
                         mu: float = 0.5):
    """Pick the QKD protocol giving the highest coexistence key rate for a route.

    Returns ``(best_protocol, best_rate, {protocol: rate})``.
    """
    rates = {p: protocol_coexistence_key_rate(
        p, distance_km, launch_dbm_per_channel, n_channels, fiber=fiber,
        detector=detector, cv_detector=cv_detector, raman=raman,
        finite=finite, mu=mu) for p in protocols}
    best = max(rates, key=rates.get)
    return best, rates[best], rates


@dataclass(frozen=True)
class OperatingPoint:
    """Result of a coexistence optimization."""

    feasible: bool
    launch_dbm: float
    classical_capacity_bps: float
    secret_key_rate: float
    qkd_constraint_binds: bool
    distance_km: float
    n_channels: int
    protocol: str

    @property
    def capacity_tbps(self) -> float:
        return self.classical_capacity_bps / 1e12


def optimize_launch_power(distance_km: float, n_channels: int,
                          min_key_rate: float, *, protocol: str = "dv",
                          fiber: FiberSpec = SMF28,
                          detector: DetectorModel | None = None,
                          cv_detector: CVDetector | None = None,
                          raman: RamanModel | None = None,
                          finite: FiniteKeyParams | None = None,
                          symbol_rate_baud: float = 32e9,
                          channel_spacing_hz: float = 50e9,
                          power_bounds_dbm: tuple[float, float] = (-30.0, 10.0)
                          ) -> OperatingPoint:
    """Maximise classical capacity subject to secret-key rate >= ``min_key_rate``.

    Works for any QKD protocol ('dv', 'cv', 'mdi', 'tf'); ``feasible`` is False if
    no launch power in ``power_bounds_dbm`` meets the key-rate requirement.
    """
    def key_rate(d, p, n):
        return protocol_coexistence_key_rate(
            protocol, d, p, n, fiber=fiber, detector=detector,
            cv_detector=cv_detector, raman=raman, finite=finite)
    lo, hi = power_bounds_dbm

    def cap(pdbm):
        return classical_capacity_bps(
            pdbm, n_channels, distance_km, fiber=fiber,
            symbol_rate_baud=symbol_rate_baud, channel_spacing_hz=channel_spacing_hz)

    # Unconstrained capacity optimum (GN optimum) over the power range.
    gn = minimize_scalar(lambda p: -cap(p), bounds=(lo, hi), method="bounded")
    p_gn = float(gn.x)

    # Secure boundary: largest launch power with key rate >= threshold.
    def margin(pdbm):
        return key_rate(distance_km, pdbm, n_channels) - min_key_rate

    if margin(lo) < 0:                       # even minimal power is insecure
        return OperatingPoint(False, float("nan"), 0.0, 0.0, True,
                              distance_km, n_channels, protocol)
    if margin(hi) >= 0:                       # secure across the whole range
        p_sec = hi
    else:
        p_sec = float(brentq(margin, lo, hi, xtol=1e-4))

    binds = p_sec < p_gn
    p_star = min(p_gn, p_sec)
    return OperatingPoint(
        True, p_star, cap(p_star), key_rate(distance_km, p_star, n_channels),
        binds, distance_km, n_channels, protocol)


def coexistence_reach(n_channels: int, min_key_rate: float,
                      min_capacity_bps: float, *, protocol: str = "dv",
                      fiber: FiberSpec = SMF28,
                      detector: DetectorModel | None = None,
                      cv_detector: CVDetector | None = None,
                      raman: RamanModel | None = None,
                      symbol_rate_baud: float = 32e9,
                      channel_spacing_hz: float = 50e9,
                      max_distance_km: float = 200.0) -> float:
    """Maximum distance (km) where some launch power meets BOTH a capacity and a
    key-rate target simultaneously.  Returns 0.0 if infeasible even at 0 km."""
    def feasible(d):
        op = optimize_launch_power(
            d, n_channels, min_key_rate, protocol=protocol, fiber=fiber,
            detector=detector, cv_detector=cv_detector, raman=raman,
            symbol_rate_baud=symbol_rate_baud, channel_spacing_hz=channel_spacing_hz)
        return op.feasible and op.classical_capacity_bps >= min_capacity_bps

    if not feasible(1.0):
        return 0.0
    # Bisect for the crossover distance.
    lo, hi = 1.0, max_distance_km
    if feasible(hi):
        return max_distance_km
    for _ in range(40):
        mid = 0.5 * (lo + hi)
        if feasible(mid):
            lo = mid
        else:
            hi = mid
    return lo
