"""Joint classical-quantum coexistence optimizer.

Turns the coexistence *calculator* into a design *tool*: given a fiber route, a
DWDM channel plan, and a quantum-security requirement, it solves for the best
classical launch power instead of sweeping by hand.

Because classical capacity is unimodal in launch power (it rises to the
Gaussian-Noise optimum, then falls) while the QKD key rate is monotonically
decreasing in launch power, the constrained optimum is simply::

    p* = min( p_GN-optimum , p_secure-boundary )

i.e. push the classical power up to its own optimum, unless QKD security forces
you to back off first.  This module finds both points (via SciPy) and returns
the operating point plus whether the QKD constraint binds.  A gradient-based
(autodiff) optimizer over more variables is the natural future upgrade.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import brentq, minimize_scalar

from iqcore.fiber import FiberSpec, SMF28
from .dv import DetectorModel, bb84_decoy_key_rate
from .cv import CVDetector
from .finite_key import FiniteKeyParams
from .protocols import mdi_qkd_key_rate, tf_qkd_key_rate
from .model_status import (
    AUTO_SELECTION_PROTOCOLS,
    PROTOCOL_MODEL_INFO,
    ModelStatus,
    ScalingProxyOptInRequired,
    protocol_model_info,
    require_scaling_proxy_opt_in,
)
from .coexistence import (
    RamanModel, classical_capacity_bps, raman_background_yield,
    coexistence_dv_key_rate, coexistence_cv_key_rate,
)

__all__ = [
    "OperatingPoint",
    "optimize_launch_power",
    "coexistence_reach",
    "protocol_coexistence_key_rate",
    "select_best_protocol",
]

QKD_PROTOCOLS = tuple(PROTOCOL_MODEL_INFO)


def protocol_coexistence_key_rate(protocol: str, distance_km: float,
                                  launch_dbm_per_channel: float, n_channels: int, *,
                                  fiber: FiberSpec = SMF28,
                                  detector: DetectorModel | None = None,
                                  cv_detector: CVDetector | None = None,
                                  raman: RamanModel | None = None,
                                  finite: FiniteKeyParams | None = None,
                                  mu: float = 0.5,
                                  allow_scaling_proxy: bool = False) -> float:
    """Secret-key rate of ``protocol`` under classical DWDM coexistence.

    Dispatches to the right protocol, injecting the spontaneous-Raman background
    (DV/MDI/TF) or excess noise (CV) generated by the co-propagating classical
    channels, and applies finite-size sensitivity corrections where supported.
    MDI and TF are labelled ``scaling_proxy`` and require the explicit
    ``allow_scaling_proxy=True`` opt-in in this high-level workflow.
    """
    proto = protocol.lower()
    require_scaling_proxy_opt_in(
        proto, allow_scaling_proxy=allow_scaling_proxy)
    det = detector or DetectorModel()
    eta = fiber.transmissivity(distance_km)
    p_total = 1e-3 * 10.0 ** (launch_dbm_per_channel / 10.0) * n_channels

    if proto == "cv":
        return coexistence_cv_key_rate(
            distance_km, launch_dbm_per_channel, n_channels, fiber=fiber,
            cv_detector=cv_detector, raman=raman, finite=finite)

    bg = raman_background_yield(p_total, distance_km, fiber=fiber, raman=raman,
                               detector_efficiency=det.efficiency)
    if proto == "dv":
        return bb84_decoy_key_rate(eta, mu, detector=det, background_yield=bg,
                                   finite=finite)
    if proto == "mdi":
        return mdi_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    if proto == "tf":
        return tf_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    raise ValueError(f"protocol must be one of {QKD_PROTOCOLS}")


def select_best_protocol(distance_km: float, n_channels: int,
                         launch_dbm_per_channel: float, *,
                         protocols=None,
                         fiber: FiberSpec = SMF28,
                         detector: DetectorModel | None = None,
                         cv_detector: CVDetector | None = None,
                         raman: RamanModel | None = None,
                         finite: FiniteKeyParams | None = None,
                         mu: float = 0.5,
                         include_scaling_proxies: bool = False):
    """Select the highest-rate recommendation-eligible coexistence model.

    By default only ``AUTO_SELECTION_PROTOCOLS`` (currently DV and CV) are
    evaluated.  Setting ``include_scaling_proxies=True`` adds MDI/TF values to
    the returned comparison dictionary, but those proxy values are *never*
    candidates for ``best_protocol``.  If all eligible models have zero rate,
    ``best_protocol`` is ``None`` rather than a misleading recommendation.

    Returns ``(best_protocol_or_none, best_eligible_rate, {protocol: rate})``.
    """
    if protocols is None:
        requested = (
            QKD_PROTOCOLS if include_scaling_proxies
            else AUTO_SELECTION_PROTOCOLS
        )
    else:
        requested = tuple(dict.fromkeys(p.lower() for p in protocols))

    metadata = {p: protocol_model_info(p) for p in requested}
    proxy_requested = [p for p, info in metadata.items() if info.is_proxy]
    if proxy_requested and not include_scaling_proxies:
        names = ", ".join(proxy_requested)
        raise ScalingProxyOptInRequired(
            f"Scaling-proxy protocol(s) requested: {names}. "
            "Set include_scaling_proxies=True to report them for exploratory "
            "comparison; they will remain excluded from selection."
        )

    eligible = [
        p for p, info in metadata.items()
        if info.automatic_recommendation_eligible
    ]
    if not eligible:
        raise ValueError(
            "select_best_protocol requires at least one automatic-"
            "recommendation-eligible protocol"
        )

    rates = {p: protocol_coexistence_key_rate(
        p, distance_km, launch_dbm_per_channel, n_channels, fiber=fiber,
        detector=detector, cv_detector=cv_detector, raman=raman,
        finite=finite, mu=mu,
        allow_scaling_proxy=include_scaling_proxies) for p in requested}
    candidate = max(eligible, key=rates.get)
    best_rate = rates[candidate]
    best = candidate if best_rate > 0.0 else None
    return best, best_rate, rates


@dataclass(frozen=True)
class OperatingPoint:
    """Result of a coexistence optimization."""

    feasible: bool
    launch_dbm: float
    classical_capacity_bps: float
    secret_key_rate: float
    qkd_constraint_binds: bool
    distance_km: float
    n_channels: int
    protocol: str
    model_status: ModelStatus = ModelStatus.RESEARCH_MODEL
    automatic_recommendation_eligible: bool = True

    @property
    def capacity_tbps(self) -> float:
        return self.classical_capacity_bps / 1e12


def optimize_launch_power(distance_km: float, n_channels: int,
                          min_key_rate: float, *, protocol: str = "dv",
                          fiber: FiberSpec = SMF28,
                          detector: DetectorModel | None = None,
                          cv_detector: CVDetector | None = None,
                          raman: RamanModel | None = None,
                          finite: FiniteKeyParams | None = None,
                          symbol_rate_baud: float = 32e9,
                          channel_spacing_hz: float = 50e9,
                          power_bounds_dbm: tuple[float, float] = (-30.0, 10.0),
                          allow_scaling_proxy: bool = False,
                          ) -> OperatingPoint:
    """Maximise classical capacity subject to secret-key rate >= ``min_key_rate``.

    DV and CV are enabled by default.  MDI/TF are scaling proxies and require
    ``allow_scaling_proxy=True``; any returned proxy operating point is labelled
    as ineligible for an automatic engineering recommendation.  ``feasible`` is
    False if no launch power in ``power_bounds_dbm`` meets the key-rate target.
    """
    info = require_scaling_proxy_opt_in(
        protocol, allow_scaling_proxy=allow_scaling_proxy)

    def key_rate(d, p, n):
        return protocol_coexistence_key_rate(
            protocol, d, p, n, fiber=fiber, detector=detector,
            cv_detector=cv_detector, raman=raman, finite=finite,
            allow_scaling_proxy=allow_scaling_proxy)
    lo, hi = power_bounds_dbm

    def cap(pdbm):
        return classical_capacity_bps(
            pdbm, n_channels, distance_km, fiber=fiber,
            symbol_rate_baud=symbol_rate_baud, channel_spacing_hz=channel_spacing_hz)

    # Unconstrained capacity optimum (GN optimum) over the power range.
    gn = minimize_scalar(lambda p: -cap(p), bounds=(lo, hi), method="bounded")
    p_gn = float(gn.x)

    # Secure boundary: largest launch power with key rate >= threshold.
    def margin(pdbm):
        return key_rate(distance_km, pdbm, n_channels) - min_key_rate

    if margin(lo) < 0:                       # even minimal power is insecure
        return OperatingPoint(False, float("nan"), 0.0, 0.0, True,
                              distance_km, n_channels, protocol,
                              info.status,
                              info.automatic_recommendation_eligible)
    if margin(hi) >= 0:                       # secure across the whole range
        p_sec = hi
    else:
        p_sec = float(brentq(margin, lo, hi, xtol=1e-4))

    binds = p_sec < p_gn
    p_star = min(p_gn, p_sec)
    return OperatingPoint(
        True, p_star, cap(p_star), key_rate(distance_km, p_star, n_channels),
        binds, distance_km, n_channels, protocol, info.status,
        info.automatic_recommendation_eligible)


def coexistence_reach(n_channels: int, min_key_rate: float,
                      min_capacity_bps: float, *, protocol: str = "dv",
                      fiber: FiberSpec = SMF28,
                      detector: DetectorModel | None = None,
                      cv_detector: CVDetector | None = None,
                      raman: RamanModel | None = None,
                      symbol_rate_baud: float = 32e9,
                      channel_spacing_hz: float = 50e9,
                      max_distance_km: float = 200.0,
                      allow_scaling_proxy: bool = False) -> float:
    """Maximum distance (km) where some launch power meets BOTH a capacity and a
    key-rate target simultaneously.  Returns 0.0 if infeasible even at 0 km.
    Scaling proxies require explicit exploratory opt-in and remain ineligible
    for engineering recommendation.
    """
    require_scaling_proxy_opt_in(
        protocol, allow_scaling_proxy=allow_scaling_proxy)

    def feasible(d):
        op = optimize_launch_power(
            d, n_channels, min_key_rate, protocol=protocol, fiber=fiber,
            detector=detector, cv_detector=cv_detector, raman=raman,
            symbol_rate_baud=symbol_rate_baud, channel_spacing_hz=channel_spacing_hz,
            allow_scaling_proxy=allow_scaling_proxy)
        return op.feasible and op.classical_capacity_bps >= min_capacity_bps

    if not feasible(1.0):
        return 0.0
    # Bisect for the crossover distance.
    lo, hi = 1.0, max_distance_km
    if feasible(hi):
        return max_distance_km
    for _ in range(40):
        mid = 0.5 * (lo + hi)
        if feasible(mid):
            lo = mid
        else:
            hi = mid
    return lo
