"""One model, every knob: how each design parameter reaches the QKD rate.

The platform's modules each capture one dependency; this module joins them so a
single call maps the *whole* parameter set -- distance, channel loading, launch
power, modulation format, pulse-shaping roll-off, FEC, and the number of ROADM
nodes on the route -- to both outputs at once: the net classical capacity and the
co-propagating QKD secret-key rate.  It is the executable version of the
dependency map: change any input and see both outputs move.

The one physical link this adds over the earlier tie-ins is **ROADM -> QKD**.
A quantum signal cannot be amplified, so every wavelength-selective switch it
passes is pure loss on the key rate:

    eta_effective = eta_fiber(distance) * 10^(-L_WSS/10),

where ``L_WSS`` is the lightpath's total WSS insertion loss
(:class:`~iqcore.fiber.Lightpath`).  The Raman background is still generated by
the classical channels in the *fiber* spans, so it is evaluated at the physical
distance -- the ROADM loss attenuates the quantum signal without adding Raman.
(For CV-QKD, whose excess-noise coexistence is computed internally, the lumped
loss is applied as an equivalent added fiber length -- a close approximation.)

So more ROADMs on a route cut the QKD rate two ways at once: directly (insertion
loss on the quantum channel) and indirectly (the classical filter-narrowing
penalty forces a higher launch power to keep the classical link closed, which
raises the Raman floor).  Both are captured here.
"""

from __future__ import annotations

from dataclasses import dataclass

from iqcore.fiber import FiberSpec, SMF28, WSSFilter, Lightpath
from iq4comm.dsp.pulse_shaping import PulseShape
from iq4comm.dsp.fec import FECCode
from .dv import DetectorModel, bb84_decoy_key_rate
from .cv import CVDetector
from .protocols import mdi_qkd_key_rate, tf_qkd_key_rate
from .coexistence import (
    RamanModel, raman_background_yield, coexistence_cv_key_rate,
)
from .finite_key import FiniteKeyParams
from .format_impact import format_capacity_bps

__all__ = [
    "roadm_insertion_loss_db",
    "system_key_rate",
    "SystemPoint",
    "system_operating_point",
]


def roadm_insertion_loss_db(n_roadms: int, wss: WSSFilter | None = None) -> float:
    """Total WSS insertion loss (dB) a lightpath sees crossing ``n_roadms`` nodes."""
    if n_roadms <= 0:
        return 0.0
    return Lightpath(n_roadms, wss or WSSFilter()).insertion_loss_db


def system_key_rate(protocol: str, distance_km: float, launch_dbm_per_channel: float,
                    n_channels: int, *, n_roadms: int = 0,
                    wss: WSSFilter | None = None, fiber: FiberSpec = SMF28,
                    detector: DetectorModel | None = None,
                    cv_detector: CVDetector | None = None,
                    raman: RamanModel | None = None,
                    finite: FiniteKeyParams | None = None, mu: float = 0.5) -> float:
    """QKD secret-key rate under DWDM coexistence *and* ROADM insertion loss.

    ROADM loss attenuates the quantum channel (``eta_eff = eta * 10^(-L/10)``)
    while the Raman background is taken at the physical distance.
    """
    proto = protocol.lower()
    det = detector or DetectorModel()
    loss_db = roadm_insertion_loss_db(n_roadms, wss)
    p_total = 1e-3 * 10.0 ** (launch_dbm_per_channel / 10.0) * n_channels

    if proto == "cv":
        # Lumped WSS loss as equivalent fiber length (CV coexistence is internal).
        d_eff = distance_km + loss_db / fiber.attenuation_db_per_km
        return coexistence_cv_key_rate(d_eff, launch_dbm_per_channel, n_channels,
                                       fiber=fiber, cv_detector=cv_detector,
                                       raman=raman, finite=finite)

    eta = fiber.transmissivity(distance_km) * 10.0 ** (-loss_db / 10.0)
    bg = raman_background_yield(p_total, distance_km, fiber=fiber, raman=raman,
                               detector_efficiency=det.efficiency)
    if proto == "dv":
        return bb84_decoy_key_rate(eta, mu, detector=det, background_yield=bg,
                                   finite=finite)
    if proto == "mdi":
        return mdi_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    if proto == "tf":
        return tf_qkd_key_rate(eta, detector=det, background_yield=bg, finite=finite)
    raise ValueError("protocol must be one of 'dv', 'cv', 'mdi', 'tf'")


@dataclass(frozen=True)
class SystemPoint:
    """Both outputs of the system at one full parameter set."""

    distance_km: float
    n_channels: int
    launch_dbm_per_channel: float
    fmt: str
    rolloff: float
    fec_name: str | None
    n_roadms: int
    channel_spacing_hz: float
    classical_capacity_bps: float
    classical_closes: bool
    roadm_loss_db: float
    secret_key_rate: float

    @property
    def capacity_tbps(self) -> float:
        return self.classical_capacity_bps / 1e12


def system_operating_point(distance_km: float, n_channels: int,
                           launch_dbm_per_channel: float, *, fmt: str = "16QAM",
                           pulse: PulseShape | None = None, fec: FECCode | None = None,
                           n_roadms: int = 0, wss: WSSFilter | None = None,
                           qkd_protocol: str = "dv", symbol_rate_baud: float = 32e9,
                           fiber: FiberSpec = SMF28,
                           detector: DetectorModel | None = None,
                           cv_detector: CVDetector | None = None,
                           raman: RamanModel | None = None,
                           finite: FiniteKeyParams | None = None,
                           mu: float = 0.5) -> SystemPoint:
    """Evaluate classical capacity and QKD key rate for one full design point.

    The pulse-shaping roll-off sets the channel spacing (hence the WDM bandwidth
    feeding the GN model); the ROADM count adds a filter-narrowing penalty to the
    classical link and insertion loss to the quantum channel; the FEC code sets
    the closure threshold and charges its overhead.  One call, both outputs.
    """
    pulse = pulse or PulseShape("rrc", 0.2)
    spacing = pulse.channel_spacing_hz(symbol_rate_baud)

    # Classical: filter-narrowing penalty (dB) reduces the effective SNR margin.
    narrowing_db = 0.0
    if n_roadms > 0:
        lp = Lightpath(n_roadms, wss or WSSFilter())
        occupied = pulse.occupied_bandwidth_hz(symbol_rate_baud)
        narrowing_db = lp.narrowing_penalty_db(occupied)

    cap, _ber, closes = format_capacity_bps(
        fmt, launch_dbm_per_channel - narrowing_db, n_channels, distance_km,
        fec=fec, fiber=fiber, symbol_rate_baud=symbol_rate_baud,
        channel_spacing_hz=spacing)

    skr = system_key_rate(qkd_protocol, distance_km, launch_dbm_per_channel,
                          n_channels, n_roadms=n_roadms, wss=wss, fiber=fiber,
                          detector=detector, cv_detector=cv_detector, raman=raman,
                          finite=finite, mu=mu)

    return SystemPoint(
        distance_km, n_channels, launch_dbm_per_channel, fmt, pulse.beta,
        (fec.name if fec is not None else None), n_roadms, spacing,
        cap, closes, roadm_insertion_loss_db(n_roadms, wss), skr)
