"""Generate a reproducible scientific validation report for iQuant4."""

from __future__ import annotations

import argparse
import importlib.util
import platform
import sys
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from iq4comm.analysis.receiver_family import (
    ReceiverFamilyConfiguration,
    compare_receiver_families,
)
from iq4comm.channels import FiberChannel
from iqcore.measurements import quadrature_statistics
from iqcore.optics import (
    apply_beam_splitter,
    beam_splitter_unitary,
    unitary_error,
)
from iqcore.phase_space import (
    wigner_function,
    wigner_negativity,
    wigner_normalization,
)
from iqcore.states import (
    basis_index,
    coherent_state,
    even_cat_state,
    fock_state,
    squeezed_vacuum_state,
    tensor_product,
)


def build_report() -> str:
    alpha = 1.5 + 0.6j
    coherent = coherent_state(alpha=alpha, cutoff=40)
    coherent_stats = quadrature_statistics(coherent, angle=0.0)

    squeezing = 0.7
    squeezed = squeezed_vacuum_state(squeezing, 0.0, 40)
    squeezed_x = quadrature_statistics(squeezed, angle=0.0)
    squeezed_p = quadrature_statistics(squeezed, angle=np.pi / 2.0)

    fiber = FiberChannel(attenuation_db_per_km=0.2)
    fiber_eta = fiber.transmittance(50.0)

    dimensions = (4, 4)
    unitary = beam_splitter_unitary(dimensions, transmissivity=0.5)
    one = fock_state(1, 4)
    hom_input = tensor_product(one, one)
    hom_output = apply_beam_splitter(
        hom_input,
        dimensions,
        transmissivity=0.5,
    )
    p20 = abs(hom_output[basis_index((2, 0), dimensions)]) ** 2
    p11 = abs(hom_output[basis_index((1, 1), dimensions)]) ** 2
    p02 = abs(hom_output[basis_index((0, 2), dimensions)]) ** 2

    grid = np.linspace(-5.0, 5.0, 121)
    cat = even_cat_state(alpha=1.5, cutoff=30)
    wigner = wigner_function(cat, grid, grid)
    wigner_norm = wigner_normalization(wigner, grid, grid)
    wigner_neg = wigner_negativity(wigner, grid, grid)

    receiver_config = ReceiverFamilyConfiguration(
        distances_km=(0.0, 20.0),
        max_pnr_threshold=10,
        homodyne_threshold_step=0.25,
        heterodyne_threshold_step=0.25,
    )
    receiver_rows = compare_receiver_families(receiver_config)

    cvxpy_status = (
        "available"
        if importlib.util.find_spec("cvxpy") is not None
        else "not installed (SDP tests are skipped)"
    )

    return f"""# Scientific validation report

This report is generated by `tools/generate_validation_report.py` from the
release-candidate source. Values are deterministic reference checks, not a
claim that all physical regimes or security models are covered.

## Runtime

| Item | Value |
|---|---|
| Python | {platform.python_version()} |
| Platform | {platform.platform()} |
| CVXPY | {cvxpy_status} |

## Analytical and numerical checks

| Capability | Numerical result | Reference/criterion |
|---|---:|---:|
| Coherent X mean | {coherent_stats.mean:.12f} | {np.sqrt(2.0) * alpha.real:.12f} |
| Coherent X variance | {coherent_stats.variance:.12f} | 0.500000000000 |
| Squeezed X variance | {squeezed_x.variance:.12f} | {0.5 * np.exp(-2.0 * squeezing):.12f} |
| Squeezed P variance | {squeezed_p.variance:.12f} | {0.5 * np.exp(2.0 * squeezing):.12f} |
| 50 km fiber transmissivity | {fiber_eta:.12f} | 0.100000000000 |
| 50:50 beam-splitter unitarity error | {unitary_error(unitary):.3e} | near machine precision |
| HOM P(2,0) | {p20:.12f} | 0.500000000000 |
| HOM P(1,1) | {p11:.3e} | 0 |
| HOM P(0,2) | {p02:.12f} | 0.500000000000 |
| Cat Wigner normalization | {wigner_norm:.12f} | approximately 1 |
| Cat Wigner negativity | {wigner_neg:.12f} | positive |

## Receiver-family regression

| Distance (km) | Winner | PNR BER | Homodyne BER | Heterodyne BER |
|---:|---|---:|---:|---:|
{chr(10).join(f'| {row.distance_km:.1f} | {row.winner} | {row.pnr.metrics.conditional_ber:.12f} | {row.homodyne.metrics.conditional_ber:.12f} | {row.heterodyne.metrics.conditional_ber:.12f} |' for row in receiver_rows)}

## Scope and limitations

- Calculations use finite Fock-space truncations.
- Several models are idealized or asymptotic.
- Communication key-rate/security claims require protocol-specific security
  analysis beyond these numerical checks.
- Passing validation establishes consistency with the documented conventions;
  it does not establish experimental calibration or composable security.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/release/validation.md"),
    )
    args = parser.parse_args()
    report = build_report()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
